[tool.poetry]
name = "idr-metadata-model"
version = "0.1.0"
description = "Fetches plates and annotations from IDR/idr-metadata on GitHub"
authors = ["Hamdah Shafqat Abbasi <hamdahshafqat.abbasi@nih.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.0"
pygithub = "^2.6.1" 
pydantic = "^2.10.6"
pandas = "^2.2.3"
typer = "^0.15.2"
requests = "^2.32.3" 

[tool.poetry.dev-dependencies]
pytest = "^8.0.0" 
black = "^24.2.0"
isort = "^5.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
idr = "src.Idr.__main__:main"